#!/bin/bash

#SBATCH --job-name=Crowding
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem 40000
#SBATCH -t 172:00:00
#SBATCH --partition="gpu"
#SBATCH --gres=gpu:1

unset OMP_NUM_THREADS

module purge

eval "$(conda shell.bash hook)"

conda activate mds

module load cuda/11.3
source /gpfs/software/soft/manual/broadwell/gromacs/2021.4-gpu/bin/GMXRC

timestamp=`date +%Y-%m-%d-%H-%M`

./naribas Kappa_input_STEP1-preparation.sh &> ${timestamp}.out
./naribas Kappa_input_STEP2-run.sh &> ${timestamp}.out
#./naribas Kappa_input_STEP3-analysis.sh &> ${timestamp}.out
#./naribas Kappa_input_STEP3b-figure.sh &> ${timestamp}.out
